### PR TITLE
personal data has been added

### PR DESCRIPTION
**Pull request by Yevhenko**

### CODE REVIEW

**Comment by Bogdan-Lishchynskiy** [comment]
please resolve conflict

**Comment by Yevhenko** [comment]
I think done

**Comment by Bogdan-Lishchynskiy** [comment]
you duplicate some users name, cretae new PR with your name below Dmytro Blokhin
Screenshot from 2021-03-31 14-00-52

**Comment by Bogdan-Lishchynskiy** [comment]
@Yevhenko make new fork of repo, and create new PR

**Pull request merged**
